### ISSUE TITLE
Header text is same color as background on darkmode.

### ISSUE THREAD

**Issue by StianOvesen** [StianOvesen/stianovesen.github.io#1]

**Comment by StianOvesen** [comment]
Dark mode disabled until fixed.

**Comment by supsa-ak** [comment]
Hi, can I solve this issue.I am participating in Hacktoberfest.

**Comment by StianOvesen** [comment]
Sure thing, @supsa-ak! I'd appreciate that a lot.

**Comment by supsa-ak** [comment]
If you want to have more feature or bugs, I am here to do work.

**Comment by StianOvesen** [comment]
Works great! Thank you for your contribution!
